### ISSUE TITLE
Can't Install on Windows and Can't Run on Steam Deck

### ISSUE THREAD

**Issue by SilvertongueRED** [AnotherPillow/CPA2SC#1]
I'm not really tech savvy, but I tried installing on steam deck with your directions and while the folder and everything installed, trying to run main.py  (right click main.py in CPA2SC directory then click "Run in Konsole") lead to it saying it couldn't even find the directory. Then trying to do it in Windows I can't even clone the first command (git clone https://github.com/anotherpillow/CPA2SC.git && cd CPA2SC) before it says "fatal: could not create work tree dir 'CPA2SC': Permission denied" which I don't understand. I even installed Python and Git on the Windows PC. I'm sorry to ask, but could you just convert one CPA mod for me I'd like to use. It's linked [here:](https://www.nexusmods.com/stardewvalley/mods/5699). I'd do it myself but I just don't know how...thank you so so much for doing all these wonderful mods for the community!

**Comment by AnotherPillow** [comment]
Try using sdvconvertergui2.On 20 Apr 2024 22:34, SilvertongueRED ***@***.***> wrote:
I'm not really tech savvy, but I tried installing on steam deck with your directions and while the folder and everything installed, trying to run main.py  (right click main.py in CPA2SC directory then click "Run in Konsole") lead to it saying it couldn't even find the directory. Then trying to do it in Windows I can't even clone the first command (git clone https://github.com/anotherpillow/CPA2SC.git && cd CPA2SC) before it says "fatal: could not create work tree dir 'CPA2SC': Permission denied" which I don't understand. I even installed Python and Git on the Windows PC. I'm sorry to ask, but could you just convert one CPA mod for me I'd like to use. It's linked here:. I'd do it myself but I just don't know how...thank you so so much for doing all these wonderful mods for the community!

**Comment by SilvertongueRED** [comment]
So, I tried out that application, pointed it toward the mod’s manifest, the application says it’s converted, but the converted mod folder is just the same format and content etc as CPA…did I do something wrong? Really sorry to bother ya the gui is very easy to understand though! Excellent work. Roland DuBoisiCloudOn Apr 20, 2024, at 5:48 PM, AnotherPillow ***@***.***> wrote:﻿
Try using sdvconvertergui2.On 20 Apr 2024 22:34, SilvertongueRED ***@***.***> wrote:

I'm not really tech savvy, but I tried installing on steam deck with your directions and while the folder and everything installed, trying to run main.py  (right click main.py in CPA2SC directory then click "Run in Konsole") lead to it saying it couldn't even find the directory. Then trying to do it in Windows I can't even clone the first command (git clone https://github.com/anotherpillow/CPA2SC.git && cd CPA2SC) before it says "fatal: could not create work tree dir 'CPA2SC': Permission denied" which I don't understand. I even installed Python and Git on the Windows PC. I'm sorry to ask, but could you just convert one CPA mod for me I'd like to use. It's linked here:. I'd do it myself but I just don't know how...thank you so so much for doing all these wonderful mods for the community!

**Comment by SilvertongueRED** [comment]
Ok! So, I was kinda wrong? The Assets folder appears the same (but maybe that didn't need to change) however the content file does indeed look very different and Spacecore format. However, the manifest file is the same...does that need to change at all?
