### ISSUE TITLE
Only keep "Changes"

### ISSUE THREAD

**Issue by Leroymilo** [AnotherPillow/CPA2SC#2]
The script only keeps the "Changes" Field of the Content Pack, it's fine because I can just copy-paste the part of the result I want but some people might loose data because of it. Missing fields are "ConfigSchema" and "DynamicTokens". The best practice would be to transfer all fields regardless of their key. 
The Animated Changes also lost their "When" Field, and I wouldn't be surprised other fields like "Update" were not transferred.

**Comment by AnotherPillow** [comment]
Sorry, just saw this now. I'll look into it soon.

**Comment by AnotherPillow** [comment]
Fixed.
